# This is a basic workflow to help you get started with Actions

name: install Linux package
description: Install Chrome, Firefox and Git on Linux
inputs:
  chrome:
    type: boolean
    required: true
  firefox:
    type: boolean
    required: true
  git:
    type: boolean
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      if: ${{ inputs.chrome }}
      run: |
        sudo apt-get install google-chrome-stable
    - shell: bash
      if: ${{ inputs.firefox }}
      run: |
        sudo apt-get install firefox
    - shell: bash
      if: ${{ inputs.git }}
      run: |
        sudo apt-get install git
